/**
 * Caption presets, kept numerically identical to the app's
 * `src/lib/captionTemplateStyles.ts`.
 *
 * Sizes are stored as a fraction of a 393 pt phone preview width and scaled by
 * the render width at draw time, so what the creator sees in the live preview is
 * what the Lambda burns — no separate "render sizing" to drift out of sync.
 */

import type {CaptionTemplateId} from '../blueprintSchema';

/** Width of the RN preview surface the presets were authored against. */
const PREVIEW_WIDTH_PT = 393;

export type CaptionAnimation =
  | 'highlight'
  | 'karaoke'
  | 'scale'
  | 'bounce'
  | 'box';

export type CaptionTemplate = {
  id: CaptionTemplateId;
  label: string;
  primaryColor: string;
  highlightColor: string;
  outlineColor: string;
  backgroundColor: string | null;
  /** Authored in preview points; convert with `captionFontSize`. */
  fontSizePt: number;
  outlineWidthPt: number;
  maxWidthFrac: number;
  animation: CaptionAnimation;
  /** Impact-style faces suit the loud presets; the rest read better in Inter. */
  weight: 'impact' | 'sans';
  uppercase: boolean;
};

export const CAPTION_TEMPLATES: Record<CaptionTemplateId, CaptionTemplate> = {
  hormozi: {
    id: 'hormozi',
    label: 'Hormozi',
    primaryColor: '#FFFFFF',
    highlightColor: '#00FFFF',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 34,
    outlineWidthPt: 5,
    maxWidthFrac: 0.9,
    animation: 'scale',
    weight: 'impact',
    uppercase: true,
  },
  mrbeast: {
    id: 'mrbeast',
    label: 'MrBeast',
    primaryColor: '#FFFF00',
    highlightColor: '#FF6600',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 38,
    outlineWidthPt: 8,
    maxWidthFrac: 0.92,
    animation: 'scale',
    weight: 'impact',
    uppercase: true,
  },
  karaoke: {
    id: 'karaoke',
    label: 'Karaoke',
    primaryColor: '#FFFFFF',
    highlightColor: '#F5B942',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 34,
    outlineWidthPt: 4,
    maxWidthFrac: 0.9,
    animation: 'karaoke',
    weight: 'impact',
    uppercase: false,
  },
  classic: {
    id: 'classic',
    label: 'Classic',
    primaryColor: '#FFFFFF',
    highlightColor: '#FFFF00',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 34,
    outlineWidthPt: 3,
    maxWidthFrac: 0.88,
    animation: 'scale',
    weight: 'impact',
    uppercase: true,
  },
  box: {
    id: 'box',
    label: 'Box',
    primaryColor: '#FFFFFF',
    highlightColor: '#FFFFFF',
    outlineColor: 'transparent',
    backgroundColor: 'rgba(0,0,0,0.72)',
    fontSizePt: 32,
    outlineWidthPt: 0,
    maxWidthFrac: 0.84,
    animation: 'box',
    weight: 'sans',
    uppercase: false,
  },
  bounce: {
    id: 'bounce',
    label: 'Bounce',
    primaryColor: '#00FF88',
    highlightColor: '#FF00FF',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 36,
    outlineWidthPt: 5,
    maxWidthFrac: 0.9,
    animation: 'bounce',
    weight: 'impact',
    uppercase: true,
  },
  minimal: {
    id: 'minimal',
    label: 'Minimal',
    primaryColor: '#FFFFFF',
    highlightColor: '#F5F5F5',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 32,
    outlineWidthPt: 4,
    maxWidthFrac: 0.86,
    animation: 'scale',
    weight: 'sans',
    uppercase: false,
  },
  clean: {
    id: 'clean',
    label: 'Clean',
    primaryColor: '#FFFFFF',
    highlightColor: '#FFFFFF',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 30,
    outlineWidthPt: 3,
    maxWidthFrac: 0.86,
    animation: 'scale',
    weight: 'sans',
    uppercase: false,
  },
  subtitle: {
    id: 'subtitle',
    label: 'Subtitle',
    primaryColor: '#F8FAFC',
    highlightColor: '#F8FAFC',
    outlineColor: '#000000',
    backgroundColor: 'rgba(0,0,0,0.45)',
    fontSizePt: 28,
    outlineWidthPt: 0,
    maxWidthFrac: 0.82,
    animation: 'box',
    weight: 'sans',
    uppercase: false,
  },
  basic: {
    id: 'basic',
    label: 'Basic',
    primaryColor: '#FFFFFF',
    highlightColor: '#FFFFFF',
    outlineColor: 'transparent',
    backgroundColor: 'rgba(55,65,81,0.82)',
    fontSizePt: 28,
    outlineWidthPt: 0,
    maxWidthFrac: 0.82,
    animation: 'box',
    weight: 'sans',
    uppercase: false,
  },
  beast: {
    id: 'beast',
    label: 'Beast',
    primaryColor: '#FFFF00',
    highlightColor: '#FF6600',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 38,
    outlineWidthPt: 8,
    maxWidthFrac: 0.92,
    animation: 'scale',
    weight: 'impact',
    uppercase: true,
  },
  hustle: {
    id: 'hustle',
    label: 'Hustle',
    primaryColor: '#00FF88',
    highlightColor: '#FF00FF',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 36,
    outlineWidthPt: 5,
    maxWidthFrac: 0.9,
    animation: 'bounce',
    weight: 'impact',
    uppercase: true,
  },
  'gaming-stream': {
    id: 'gaming-stream',
    label: 'Gaming',
    primaryColor: '#FFFFFF',
    highlightColor: '#00FFFF',
    outlineColor: '#111111',
    backgroundColor: null,
    fontSizePt: 34,
    outlineWidthPt: 4,
    maxWidthFrac: 0.9,
    animation: 'highlight',
    weight: 'impact',
    uppercase: true,
  },
  pop: {
    id: 'pop',
    label: 'Pop',
    primaryColor: '#FFFFFF',
    highlightColor: '#F8FAFC',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 34,
    outlineWidthPt: 4,
    maxWidthFrac: 0.88,
    animation: 'bounce',
    weight: 'sans',
    uppercase: false,
  },
  grape: {
    id: 'grape',
    label: 'Grape',
    primaryColor: '#FFFFFF',
    highlightColor: '#F5D0FE',
    outlineColor: 'transparent',
    backgroundColor: 'rgba(109,40,217,0.92)',
    fontSizePt: 32,
    outlineWidthPt: 0,
    maxWidthFrac: 0.84,
    animation: 'box',
    weight: 'sans',
    uppercase: false,
  },
  poppin: {
    id: 'poppin',
    label: 'Poppin',
    primaryColor: '#FFFFFF',
    highlightColor: '#F97316',
    outlineColor: '#111111',
    backgroundColor: null,
    fontSizePt: 36,
    outlineWidthPt: 4,
    maxWidthFrac: 0.9,
    animation: 'bounce',
    weight: 'impact',
    uppercase: true,
  },
  aarit: {
    id: 'aarit',
    label: 'Aarit',
    primaryColor: '#E2E8F0',
    highlightColor: '#38BDF8',
    outlineColor: '#0F172A',
    backgroundColor: null,
    fontSizePt: 36,
    outlineWidthPt: 3,
    maxWidthFrac: 0.9,
    animation: 'highlight',
    weight: 'impact',
    uppercase: true,
  },
  'soft-ai': {
    id: 'soft-ai',
    label: 'Soft AI',
    primaryColor: '#F8FAFC',
    highlightColor: '#FFFFFF',
    outlineColor: 'transparent',
    backgroundColor: 'rgba(15,23,42,0.45)',
    fontSizePt: 32,
    outlineWidthPt: 0,
    maxWidthFrac: 0.86,
    animation: 'scale',
    weight: 'sans',
    uppercase: false,
  },
  'simple-one-word': {
    id: 'simple-one-word',
    label: 'One word',
    primaryColor: '#FFFFFF',
    highlightColor: '#FACC15',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 40,
    outlineWidthPt: 5,
    maxWidthFrac: 0.88,
    animation: 'scale',
    weight: 'sans',
    uppercase: false,
  },
  'kinetic-01': {
    id: 'kinetic-01',
    label: 'Kinetic',
    primaryColor: '#94A3B8',
    highlightColor: '#F8FAFC',
    outlineColor: '#020617',
    backgroundColor: null,
    fontSizePt: 38,
    outlineWidthPt: 4,
    maxWidthFrac: 0.92,
    animation: 'scale',
    weight: 'impact',
    uppercase: true,
  },
  'weight-shift': {
    id: 'weight-shift',
    label: 'Weight shift',
    primaryColor: '#94A3B8',
    highlightColor: '#FFFFFF',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 34,
    outlineWidthPt: 3,
    maxWidthFrac: 0.88,
    animation: 'scale',
    weight: 'sans',
    uppercase: false,
  },
  'editorial-emphasis': {
    id: 'editorial-emphasis',
    label: 'Editorial',
    primaryColor: '#FFFFFF',
    highlightColor: '#FFFFFF',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 32,
    outlineWidthPt: 3,
    maxWidthFrac: 0.86,
    animation: 'highlight',
    weight: 'sans',
    uppercase: false,
  },
  'kinetic-slam': {
    id: 'kinetic-slam',
    label: 'Slam',
    primaryColor: '#F8FAFC',
    highlightColor: '#FACC15',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 42,
    outlineWidthPt: 6,
    maxWidthFrac: 0.92,
    animation: 'scale',
    weight: 'impact',
    uppercase: true,
  },
  'moving-pill': {
    id: 'moving-pill',
    label: 'Pill',
    primaryColor: '#F8FAFC',
    highlightColor: '#111111',
    outlineColor: 'transparent',
    backgroundColor: 'rgba(8,8,12,0.42)',
    fontSizePt: 32,
    outlineWidthPt: 0,
    maxWidthFrac: 0.86,
    animation: 'box',
    weight: 'sans',
    uppercase: false,
  },
  'pop-theme': {
    id: 'pop-theme',
    label: 'Pop theme',
    primaryColor: '#FFFFFF',
    highlightColor: '#F8FAFC',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 34,
    outlineWidthPt: 4,
    maxWidthFrac: 0.88,
    animation: 'bounce',
    weight: 'sans',
    uppercase: false,
  },
  'karaoke-theme': {
    id: 'karaoke-theme',
    label: 'Karaoke theme',
    primaryColor: '#FFFFFF',
    highlightColor: '#F5B942',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 34,
    outlineWidthPt: 4,
    maxWidthFrac: 0.9,
    animation: 'karaoke',
    weight: 'impact',
    uppercase: false,
  },
  'hustle-theme': {
    id: 'hustle-theme',
    label: 'Hustle theme',
    primaryColor: '#00FF88',
    highlightColor: '#FF00FF',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 36,
    outlineWidthPt: 5,
    maxWidthFrac: 0.9,
    animation: 'bounce',
    weight: 'impact',
    uppercase: true,
  },
  'grape-theme': {
    id: 'grape-theme',
    label: 'Grape theme',
    primaryColor: '#FFFFFF',
    highlightColor: '#F5D0FE',
    outlineColor: 'transparent',
    backgroundColor: 'rgba(109,40,217,0.92)',
    fontSizePt: 32,
    outlineWidthPt: 0,
    maxWidthFrac: 0.84,
    animation: 'box',
    weight: 'sans',
    uppercase: false,
  },
  'beast-theme': {
    id: 'beast-theme',
    label: 'Beast theme',
    primaryColor: '#FFFF00',
    highlightColor: '#FF6600',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 38,
    outlineWidthPt: 8,
    maxWidthFrac: 0.92,
    animation: 'scale',
    weight: 'impact',
    uppercase: true,
  },
  'poppin-theme': {
    id: 'poppin-theme',
    label: 'Poppin theme',
    primaryColor: '#FFFFFF',
    highlightColor: '#F97316',
    outlineColor: '#111111',
    backgroundColor: null,
    fontSizePt: 36,
    outlineWidthPt: 4,
    maxWidthFrac: 0.9,
    animation: 'bounce',
    weight: 'impact',
    uppercase: true,
  },
  'aarit-theme': {
    id: 'aarit-theme',
    label: 'Aarit theme',
    primaryColor: '#E2E8F0',
    highlightColor: '#38BDF8',
    outlineColor: '#0F172A',
    backgroundColor: null,
    fontSizePt: 36,
    outlineWidthPt: 3,
    maxWidthFrac: 0.9,
    animation: 'highlight',
    weight: 'impact',
    uppercase: true,
  },
  'soft-ai-theme': {
    id: 'soft-ai-theme',
    label: 'Soft AI theme',
    primaryColor: '#F8FAFC',
    highlightColor: '#FFFFFF',
    outlineColor: 'transparent',
    backgroundColor: 'rgba(15,23,42,0.45)',
    fontSizePt: 32,
    outlineWidthPt: 0,
    maxWidthFrac: 0.86,
    animation: 'scale',
    weight: 'sans',
    uppercase: false,
  },
  'gaming-stream-theme': {
    id: 'gaming-stream-theme',
    label: 'Gaming theme',
    primaryColor: '#FFFFFF',
    highlightColor: '#00FFFF',
    outlineColor: '#111111',
    backgroundColor: null,
    fontSizePt: 34,
    outlineWidthPt: 4,
    maxWidthFrac: 0.9,
    animation: 'highlight',
    weight: 'impact',
    uppercase: true,
  },
  'simple-one-word-theme': {
    id: 'simple-one-word-theme',
    label: 'One word theme',
    primaryColor: '#FFFFFF',
    highlightColor: '#FACC15',
    outlineColor: '#000000',
    backgroundColor: null,
    fontSizePt: 40,
    outlineWidthPt: 5,
    maxWidthFrac: 0.88,
    animation: 'scale',
    weight: 'sans',
    uppercase: false,
  },
  'kinetic-01-theme': {
    id: 'kinetic-01-theme',
    label: 'Kinetic theme',
    primaryColor: '#94A3B8',
    highlightColor: '#F8FAFC',
    outlineColor: '#020617',
    backgroundColor: null,
    fontSizePt: 38,
    outlineWidthPt: 4,
    maxWidthFrac: 0.92,
    animation: 'scale',
    weight: 'impact',
    uppercase: true,
  },
};

export function captionTemplateFor(id: string): CaptionTemplate {
  return (
    CAPTION_TEMPLATES[id as CaptionTemplateId] ?? CAPTION_TEMPLATES.clean
  );
}

export function scaleFromPreview(valuePt: number, renderWidth: number): number {
  return (valuePt / PREVIEW_WIDTH_PT) * renderWidth;
}
